### ISSUE TITLE
Google Fonts for better discord not showing up

### ISSUE THREAD

**Issue by magstersnoyl** [notmike101/notmike101#1]
![Better Discord Fonts settings](https://user-images.githubusercontent.com/30097599/150730269-94f66e42-83e0-4f3c-9ade-3be2f902c768.png)
I am having this weird problem where I am not able to customize my fonts anymore. The plug-in loads and says that it is working, however, when I go into it's settings, I am only able to select the default discord font. Hopefully this hasn't been a common issue for others. I hope you are able to help me figure out what is going on, thanks! I appreciate it! :)

**Comment by notmike101** [comment]
Will look into it today.

**Comment by notmike101** [comment]
Being addressed here:
https://github.com/notmike101/betterdiscord-google-fonts/issues/3
